### PR TITLE
Gradle build file added for Android submodule integration

### PR DESCRIPTION
**Pull request by koh-osug**
I have to integrate the project as sub module in a Gradle project.

### CODE REVIEW

**Comment by chhsiao90** [comment]
Hi @koh-osug ,

It's a little confused to have both build system (maven, gradle).
How about I release this project to maven central so you can include this library as a dependency in your project?

**Comment by koh-osug** [comment]
Yes, this would be an option. Currently I'm integrating this into an Android project and being able to live edit the code in a sub module is quite handy.

**Comment by chhsiao90** [comment]
I will have a release today, and will reply in this thread once I have released it.

**Comment by chhsiao90** [comment]
nitmproxy released: https://search.maven.org/artifact/com.github.chhsiao90/nitmproxy/1.0.0/jar

**Comment by koh-osug** [comment]
Thanks a lot.

**Pull request closed without merging**
