### PR TITLE
nitmproxy v2.0.0

### PR DESCRIPTION
**Pull request by chhsiao90**
1. Merge HttpListener and FowardListener into NitmProxyListener
2. Initial support for response modification
3. Add listener.onInit (called on channel first initialized)
4. Add listener.onConnect (called on server channel connected)
5. Add listener.close (called on channel closed, to provide the change for users to release the resources)
6. Rename websocket functions to onWsRequest, onWsResonse (it's more clearly)

### CODE REVIEW

**Comment by chhsiao90** [comment]
@abbasvalliani 

Example code for http response intercept can be found [here](https://github.com/chhsiao90/nitmproxy-examples/blob/master/src/main/java/com/github/chhsiao90/nitmproxy/examples/HttpResponseInterceptor.java)

It looks complicated, I will create some template interceptors to simplify the intercept process in separate PR.

**Comment by kaoh** [comment]
Yes, I will check it. My setup is a local MITM proxy and an Android project.

**Comment by abbasvalliani** [comment]
@chhsiao90 My initial gut feeling looking at this is the level of complexity for the user. Any chance we can simplify this while still providing the control (if needed). I don't have an issue using the API as is, but could be cumbersome for someone new.

**Comment by abbasvalliani** [comment]
@chhsiao90 Any chance we can do a release of 2.0? Thanks!

**Comment by chhsiao90** [comment]
nitmproxy v2.0.0 just released

**Pull request merged**
