### PR TITLE
Makes tls more configurable

### PR DESCRIPTION
**Pull request by chhsiao90**

### CODE REVIEW

**Comment by chhsiao90** [comment]
Hi @kaoh

After investigation, I found the Conscrypt from the Android library was repackaged which is not compatible with Netty.
I expose the ssl provider to be configurable. So Android issue can be fixed by add the [conscrypt-android](https://mvnrepository.com/artifact/org.conscrypt/conscrypt-android) to the dependency manually, and configure the ssl provider with `Conscrypt.newProvider()`.

Also, I makes the tls protocols to be configurable instead of trying to get the supported tls protocols.

**Comment by koh-osug** [comment]
This means this conscrypt android version can be used as a replacement and does not have the defects of supporting TLSv1.3 and ALPN?

**Comment by chhsiao90** [comment]
I think it should work!

**Comment by koh-osug** [comment]
Very nice, I will check it out.

**Comment by koh-osug** [comment]
Indeed, all my test are still working. Under Android the gradle dependency must include:

~~~
implementation group: 'org.conscrypt', name: 'conscrypt-android', version: '2.5.2'
~~~

Please add it to the README.

**Comment by chhsiao90** [comment]
Great!

**Pull request merged**
