### PR TITLE
Added proxy status and onStart and onStop event listener

### PR DESCRIPTION
**Pull request by abbasvalliani**
When the proxy is run through an async process, we need notifications when the server has completely started and stopped along with a status.

### CODE REVIEW

**Comment by abbasvalliani** [comment]
@chhsiao90 Is there a way to push this to a new release on maven central?

**Comment by chhsiao90** [comment]
I will publish a new release asap

**Comment by chhsiao90** [comment]
I just published 1.2.1, it should be available soon (maybe hours later) in maven central.

**Comment by abbasvalliani** [comment]
Thanks!

**Pull request merged**
